using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Net6HrPublicLibrary.PublicShared
{
    public class DbUserSybase
    {

        public readonly static string _NewEncodeEncrypt = "b14ca5898utmD2022bce2ea2315a7590";
        public readonly static string _UpnmdbDbConnProd = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLAwlGg8ZDopmUX8T6JgRQCAMPURcDVFIWFuxp2zAoPJYMxRF79r3Obc7VzAE0TMpiaGK88zg2hzI3tdUgAlgSLASHQx4nbHbUDM3c4kfVtfJvrJEVK82UWFDDkD6upEhbDpQlfI54CAMPUR5cWiKnJJQIHPnXSLASHzfEnSgQnXcOJxXT0fDF4eTErxAaMM=";
        public readonly static string _UpnmdbDbConnPScn = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLAnDSLASHjQCAMPURH1UD45B4CfnHu4fXnqyyY1Wodd83SLASHPGeQIuQvCgGXTMaMxNEtmfC7sn8pAprPIP0b6NIs7SyLSrKgWSjPzu3ppzEitdoqJEPjXxGcRQhIS1YNrv4Ycq4gpQdloQX07DM4SLASHg0oSLASHHwem8am5XAujyPdI7cQEiTUmgMbGKNw=";
        public readonly static string _UpnmdbDbConnDev = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLA7aya0KNPPWjNRoJ3lU7SLASHBABo77CkKsRACBAGCAMPURyfu9TM6EwZlG2VXCAMPURCAMPURGaowA6KxhUCrQ4dugaULtihB1QCAMPURunHdBScSLASH1WFpVh1DktwLthitO0QB1FyY8nEEnsqbVHscvCTLqQqYZlSLASHxnDMBLl9apGQVYpQHhtNbccOQCAMPURrpEOfbHuc=";
        public readonly static string _UpnmdbDbConnAkad = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLAnDSLASHjQCAMPURH1UD45B4CfnHu4fXnqyyY1Wodd83SLASHPGeQIuQvCgGXTMaMxNEtmfC7sn8pAprPIP0b6NIs7SyLSrKgWSjPzu3ppzEitdoqJEPjXxGcRQhIS1YNrv4Ycq4gpQdloBpfEa1krrYFpmc0Wf5g9DRKZYq7xQTOFCX7Xm6RPzoEMkCAMPUR6JnGaJLMtVjASB4WZD";
        public readonly static string _UpnmdbDbConnSmu = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLAwlGg8ZDopmUX8T6JgRQCAMPURcDVFIWFuxp2zAoPJYMxRF79r3Obc7VzAE0TMpiaGK88zg2hzI3tdUgAlgSLASHQx4nbHbUDM3c4kfVtfJvrJEVK82UXTAsYX1G2XW7SLASHCPrfHcWBTaKkLmex2e9IubTSLASH4TQuQkvSLASHVVga6jcj7LSqYc7cYZSLASHs=";
        public readonly static string _UpnmdbDbConnPesara = @"OEHWE98hiOSLASH1Gw1YvCySII6nasCLc5CAMPURdDwDW6hoSLASHofW0qie60BjWTkTHZebO2NLA7aya0KNPPWjNRoJ3lU7SLASHBABo77CkKsRACBAGCAMPURyfu9TM6EwZlG2VXCAMPURCAMPURGaowA6KxhUCrQ4dugaULtihB1QCAMPURunHdBScSLASH1WFpVh1DktwLthitO0QB1FyY8nEEnsqbVHscvCTs5k4EnDpMwYswJ4ZfpmLirgf1JOQAHI6Up8jP4TubxY=";

    }
}
